<html>
  <head>
    <title>index page</title>
    
      
    <!-- build:css -->
        <!-- vendor:css -->
        <!-- endinject -->
        <!-- dev:css -->
        <!-- endinject -->
      <!-- endbuild -->
    
  </head>
  <body>
    <h1>Hi there, {{firstName}} {{lastName}}. What's up dude?</h1>
    
    <!-- build-vendor:js -->
    <!-- endbuild-vendor -->
    <!-- build:js -->
    
      <!-- vendor:js -->
      <!-- endinject -->
      <!-- dev:js -->
      <!-- endinject -->
    <!-- endbuild -->

    
  </body>
</html>